import = ["/Users/pawel/.config/alacritty/gruvbox-light.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 16

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[window]
decorations = "buttonless"
dynamic_padding = false
dynamic_title = false
opacity = 0.8
startup_mode = "Maximized"
title = "alacritty"
