version: '3'

tasks:
  rebuild:
    desc: "rebuilds the configuration if `init` was launched at least once."
    preconditions:
      - nix --version
    cmds:
      - darwin-rebuild switch --flake .

  init:
    desc: "build & apply the system configuration."
    preconditions:
      - nix --version
    cmds:
      - cmd: |
          nix build .#darwinConfigurations.mb.system \
          --extra-experimental-features 'nix-command flakes' && \
          ./result/sw/bin/darwin-rebuild switch --flake .#mb
